# Numpy Exercise - Solution

In this notebook, you will complete the `# Todo` sections in the following code cells with proper numpy operations. All of the answers are available in this [Numpy reference website](https://docs.scipy.org/doc/numpy/reference/index.html). Search for the operations there, and, as you do so, you will inevitably read the documentation. You will master numpy in no time!

In [1]:
from tester import *
import numpy as np

**1. Build a numpy array of 10 rows x 4 columns. This array should contain random values from a standard normal distribution with mean of 0**

`np.random.rand()` picks random numbers from a uniform distribution, so we cannot use that. What function should we use instead? 

In [2]:
# Todo
np.random.seed(1)
answer_1 = np.random.rand(10, 4)

In [3]:
# View the data here
answer_1

array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01],
       [1.46755891e-01, 9.23385948e-02, 1.86260211e-01, 3.45560727e-01],
       [3.96767474e-01, 5.38816734e-01, 4.19194514e-01, 6.85219500e-01],
       [2.04452250e-01, 8.78117436e-01, 2.73875932e-02, 6.70467510e-01],
       [4.17304802e-01, 5.58689828e-01, 1.40386939e-01, 1.98101489e-01],
       [8.00744569e-01, 9.68261576e-01, 3.13424178e-01, 6.92322616e-01],
       [8.76389152e-01, 8.94606664e-01, 8.50442114e-02, 3.90547832e-02],
       [1.69830420e-01, 8.78142503e-01, 9.83468338e-02, 4.21107625e-01],
       [9.57889530e-01, 5.33165285e-01, 6.91877114e-01, 3.15515631e-01],
       [6.86500928e-01, 8.34625672e-01, 1.82882773e-02, 7.50144315e-01]])

In [4]:
# Check if your answer is correct here
assert_answer_1(answer_1)

Shape is correct!
Values are correct!


**2. Sum the columns. We should get an array with the shape of 1 x 4**

In [5]:
# Todo
answer_2 = np.sum(answer_1, axis=0)

In [6]:
# View
answer_2

array([5.07365702, 6.89708879, 1.98032425, 4.41982677])

In [7]:
# Check
assert_answer_2(answer_2)

Passed!


**3. Get the maximum value in each column of your first answer.**

In [8]:
# Todo
answer_3 = np.amax(answer_1, axis=0)

In [9]:
# View
answer_3

array([0.95788953, 0.96826158, 0.69187711, 0.75014431])

In [10]:
# Check
assert_answer_3(answer_3)

Passed!


**4. Let's try combining two operations. Get the first answer again, and then, for each column, calculate the percent difference between the maximum value and the last row's value, then round the results to two decimal values.**

This is more complex than the previous tasks. First, you'll need to find the maximum value in each column. Then, find out the percent difference between the last element and that value.

In [11]:
# Todo
high = np.amax(answer_1, axis=0)
answer_4 = np.around((answer_1[-1] - high) / high * 100, decimals=2)

In [12]:
# View
answer_4

array([-28.33, -13.8 , -97.36,   0.  ])

In [13]:
# Check
assert_answer_4(answer_4)

Passed!


**5. Find the dot product of these two numpy arrays below (since this is a dot product, the answer should be a 3 rows x 1 col matrix)**

In [14]:
# Todo
np.random.seed(1)

a = np.random.rand(3,3)
b = np.random.rand(3,1)
answer_5 = np.dot(a, b)

In [15]:
# View
answer_5

array([[0.52673288],
       [0.28769332],
       [0.51709009]])

In [16]:
# Check
assert_answer_5(answer_5)

Passed!
